### ISSUE TITLE
NFC 관련 검토할 사항

### ISSUE THREAD

**Issue by Dictor** [osamhack2020/IoT_LeaveItUs_797IsPalindrome#2]
라커측 NFC 리더는 하나고 수납되는 태그는 여러갠데 1:N 통신 가능?

**Comment by ndkim11** [comment]
NFC는 한번에 여러개를 찍지는 않고 순서대로 태그 찍으니까 상관 없을듯.
NFC 태그를 배열에 담고 하나씩 비교해서 맞으면 그 태그 해당하는 폰에 관한 처리할 계획임

**Comment by Dictor** [comment]
@ndkim11 
오키, 내가 생각한 방식이랑 너가 생각한 방식이랑 좀 다른것 같아서, 요약할테니 보고 적절한거 선택한담에 이 이슈 닫아주면 될듯.

**내 안**: NFC 리더가 일정 주기마다 보관함안의 모든 태그를 스캔하여 들어가있는지 판단하고 무게와 도어 센서는 보조용임. 편법에 방어하기 쉬우나 구현과 하드웨어가 복잡함. 1:n 스캔이 되면 nfc 리더가 하나면 되지만 안될경우 휴대폰 수납칸마다 리더를 배치해야함.

**너 안**: 휴대폰 반납/불출시 NFC 태그하고 수납. 휴대폰이 태그된 후 정말 들어갔는지는 도어와 무게로 판단. 다만 무게를 속이면 방어할 방법이 없음. 구현이 쉬움.

**Comment by ndkim11** [comment]
1:N 방식의 NFC 통신 방식은 생각을 못해봤고 아직 못 알아봤음.
구멍에 들어갈 크기의 비슷한 무게의 물건을 구한다면 보관함을 통한 방어는 불가하지만, 보관함 문의 재질을 투명하게 해놓거나 소요계/보안과 등에서 검문을 나올 수 있다는 것을 감안하면 불안감을 자극함으로써 방어가 가능하지 않을까라는게 내 생각임. 소요계나 보안과를 속이기 위해서는 오차범위 내에 들어갈 무게의 휴대폰을 구하는것이 필요한데 이는 좀 어려움이 있지 않을까 싶다.
