### ISSUE TITLE
보관함 처리의 경량화를 위하여 Task 정리

### ISSUE THREAD

**Issue by ndkim11** [osamhack2020/IoT_LeaveItUs_797IsPalindrome#3]
**보관함에서 처리할 것들**
(기존) -> (개선 후)
1)불출자 명단,태그, 무게를 웹에서 받아온 후 미반납자를 보관함에서 처리      ----->  불출자 명단 X, 무게 비교 결과 배열과 태그를 보내고 서버에서 처리

2)웹에서 핸드폰 불출 시간 보냄 문개폐 센서 값을 통해 임의 불출 확인 ----->    센서 값을 읽고 개/폐만 보냄, 서버에서 임의 불출 판단?

3)각 생활관별 허가된 RFID UID를 받아옴 ----->  NFC 태그에 읽힌 UID만 보내줌,                                                                      서버에서 적합여부 판단
정리한 내용이 너가 의도한게 맞나 한번 확인해줘 @Dictor

**Comment by Dictor** [comment]
@ndkim11 
> 불출자 명단 X, 무게 비교 결과 배열과 태그를 보내고 서버에서 처리

라커는 자신에게 소속된 휴대폰의 명단(태그 UID가 들어있는)을 받아옴.
하지만 무게는 측정결과만 보내고, 현재 자신에게 보관된 태그의 배열도 보냄


> 센서 값을 읽고 개/폐만 보냄, 서버에서 임의 불출 판단?

현재 단계에서는 문 센서는 라커 자체적으로 판단을 위해서와 서버에서 단순 개폐시간 기록을 위해 수신할 뿐,
서버에서 문 개폐 시간으로 불출에 대해 판단하지는 않음. 임의 불출시 꺼내서 NFC 찍는게 아니면 불출된 휴대폰을 판단할 방법이 없다고 생각함. (#2 참고)

> NFC 태그에 읽힌 UID만 보내줌, 서버에서 적합여부 판단

이건 얼추 맞음. 현재 보관하고 있는 태그의 UID들을 보내면 됨.
(반납 시) → 라커 NFC 리더에 태깅 → 문 개폐후 휴대폰 수납 → (반출 시) → 문 개폐 후 휴대폰 불출 → 라커 NFC 리더에 태깅
이때 **라커 NFC 리더에 태깅**와 **라커 NFC 리더에 태깅** 사이 상태의 태그 UID를 라커에서 관리하면서 주기적 서버로 보내주면 됨.

**Comment by Dictor** [comment]
[여기](https://github.com/osamhack2020/WEB_LeaveItUs_797IsPalindrome/blob/master/document/web_locker_api.md)에 API 명세가 있다.

**Comment by ndkim11** [comment]
@Dictor 
> 현재 단계에서는 문 센서는 라커 자체적으로 판단을 위해서와 서버에서 단순 개폐시간 기록을 위해 수신할 뿐,
> 서버에서 문 개폐 시간으로 불출에 대해 판단하지는 않음. 

나는 서버에서 미허가 불출을 입력된 허가 시간 외에 문이 열렸을 경우 이를 알린다 이렇게 생각하고 있었거든. 맨 처음에는 서버에서 일별로 불출 시간, 반납시간을 입력 받아서 그거 외에 개폐센서 값이 열림으로 나타날 경우에 서버에 알림보냄. 근데 그걸 서버단에서 처리할까 싶었음. 아니면 사관이 웹 페이지에서 폰 불출/ 반납 버튼 누르는것 만들수 있다면 그 버튼의 상태로 보관함에서 처리할 수도 있을듯

**Comment by ndkim11** [comment]
방금 올라왔네 함 읽어볼게

**Comment by Dictor** [comment]
> 나는 서버에서 미허가 불출을 입력된 허가 시간 외에 문이 열렸을 경우 이를 알린다 이렇게 생각하고 있었거든. 
 맨 처음에는 서버에서 일별로 불출 시간, 반납시간을 입력 받아서 그거 외에 개폐센서 값이 열림으로 나타날 경우에 서버에 알림보냄. 근데 그걸 서버단에서 처리할까 싶었음.

옥히, 이건 올린 API 만으로 서버에서 처리 방식만 바꿔서 충분히 구현할 수 있음. 라커 입장에선 상관없을듯.

> 서버에서 문 개폐 시간으로 불출에 대해 판단하지는 않음.

이 말은 문 개폐 시간으로 어떤 핸드폰이 불출됬는지 판단하지 않을거라는 말임. 문에 관련된 알림은 충분히 가능!
